FROM bcgsc/orca-4:2017.08.23
RUN brew install paml
RUN brew install pandaseq
RUN brew install parallel
RUN brew install parsnp
RUN brew install pathd8
RUN brew install pathvisio
# RUN brew install pbh5tools no formulae
# RUN brew install pbsuite 
RUN brew install pcre
RUN brew install pear
RUN brew install phipack
RUN brew install phlawd
RUN brew install phylip
RUN brew install phyml
RUN brew install phyutility
#RUN brew install phyx
RUN brew install picard-tools
RUN brew install piler
RUN brew install pilercr
RUN brew install pilon
RUN brew install pixman
# RUN brew install platanus no formulae
RUN brew install plink
RUN brew install pkg-config
# RUN brew install plink2
RUN brew install poa
# RUN brew install populations
RUN brew install poretools
RUN brew install prodigal
RUN brew install prokka
RUN brew install proteinortho
RUN brew install psmc
# RUN brew install quaff
# RUN brew install quake
RUN brew install quast
RUN brew install quest
RUN brew install quorum
# RUN brew install r8s
RUN brew install racon 
RUN brew install rampart \
rapsearch2 \
raxml \
ray \
rcorrector \
readline \
readseq \
readsim \
# RUN brew install reapr
recon \
repeatmasker \
repeatmodeler \
repeatscout \
rmblast \
rna-star \
rnammer \
ropebwt2
