language: nodejs
sudo: required

services:
  - docker

before_install:
  - npm install -g dockerfile_lint

before_script:
  # Validate Docker files
  # - dockerfile_lint -f Dockerfile -r dockerfile_rules.yaml

script:
  - find . -name Dockerfile | xargs -i dockerfile_lint -f {} -r dockerfile_rules.yaml
