language: nodejs
sudo: required

services:
  - docker

before_install:
  - npm install -g dockerfile_lint

before_script:
  # Validate Docker files
   - dockerfile_lint -f Dockerfile -r dockerfile_rules.yml
   
script:
  - find . -name Dockerfile | xargs dockerfilelint
  - for dockerDir in *; do make $dockerDir; done
