language: nodejs
sudo: required

services:
  - docker

before_install:
  - npm install -g dockerfile_lint

script:
  - find . -name Dockerfile | xargs -i dockerfile_lint -f {} -r dockerfile_rules.yaml