  profile:
    name: "Default"
    description: "Ignores error messages."
  line_rules:
    FROM:
      rules:
        -
          label: "is_latest_tag"
          regex: /latest/
          level: "info"
          message: "base image uses 'latest' tag"
          description: "using the 'latest' tag may cause unpredictable builds. It is recommended that a specific tag is used in the FROM line."
          reference_url:
            - "https://docs.docker.com/engine/reference/builder/"
            - "#from"
    RUN:
      rules:
       -
         label: "sudo_use"
         regex: /sudo/
         level: "info"
         message: "Use Of sudo Is Not Allowed"
         description: "You should avoid installing or using `sudo` since it has unpredictable TTY and signal-forwarding behavior that can cause more problems than it solves."
         reference_url:
            - "https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/"

