FROM bcgsc/orca-5:2017.08.23
RUN brew install sailfish \
salmon \
sambamba \
samblaster \
samtools@0.1 \
samtools \
scarpa \
sdsl-lite \
seqan \
seqtk \
sequel \
sga \
shrimp \
sickle \
simulate-pcr \
skewer \
smalt \
# RUN brew install smrtanalysis
# snap-aligner \ may be exclude
snap \
snoscan \
snp-sites \
snpeff \
soapdenovo \
sortmerna \
spaced \
spades \
# sparseassembler \ no formulae
spici \
sqlite \
squeezambler \
sratoolkit \
ssake \
# sspace \ no formulae
# sspace-longread \ no formulae
stacks \
stringtie \
szip \
swarm
RUN brew install tagdust \ 
tasr \
tbb \
tbl2asn \
tophat \
trans-abyss \ 
#RUN brew install trans_proteomic_pipeline 
transdecoder \
transrate-tools \
trf \
trimadap \
trimal \
trimmomatic \
trinity \
trnascan 
#RUN brew install ucsc-genome-browser
RUN brew install unicycler
RUN brew install uproc
RUN brew install vague \
varscan \
vcake \
vcflib \
vcftools \
velvet \
velvetoptimiser \
viennarna \
vsearch \
vt 
RUN brew install weblogo
RUN brew install wiggletools
RUN brew install yaha
