FROM bcgsc/orca-2:2017.09.26

RUN brew install canu \
cap3 \
cd-hit \
cegma \
celera-assembler \
centrifuge \
cerulean \
circlator \
clark \
clonalframeml \
clonehd \
clustal-omega \
clustal-w \
cmake \
cutadapt \
curl \
# cufflinks \ add later, brew linkage fails
# RUN brew install corset
cytoscape
RUN brew install daligner \
dazz_db \
delly \
dextractor \
diamond \
dida \
discovar \
# discovardenovo error =(
dsk \
dwgsim
RUN brew install e-mem \
edirect \
emacs \
# RUN brew install ensembl-tools no formulae
exonerate 
# express

RUN brew install fasta \
fastml \
fastq-tools \
fastqc \
fasttree \
fastuniq \
fastx_toolkit \
fermi-lite \
fermi \
fermi2 \
fermikit \
flash \
flex \
fqzcomp \
freebayes \
freec \
fsa \
fwdpp

RUN brew install gaemr
# RUN brew install garli
RUN brew install gatb
RUN brew install gatk
RUN brew install geneid
RUN brew install genewise
RUN brew install genometools

#no such formulae
# RUN brew install gfatools

RUN brew install gingr
RUN brew install glimmerhmm
RUN brew install gmap-gsnap
RUN brew install gnuplot # broke by mummer
RUN brew install grabix
RUN brew install graphlan \
graphviz
RUN brew install gsl
# RUN brew install gubbins
RUN brew install harfbuzz
# RUN brew install harvest-tools
RUN brew install hisat
RUN brew install hisat2
RUN brew install hlaminer
RUN brew install hmmer
RUN brew install hmmer2
#RUN brew install htqc
RUN brew install htsbox
RUN brew install htslib
RUN brew install humann2
RUN brew install icu4c
RUN brew install idba
RUN brew install igv
RUN brew install igvtools
RUN brew install impute2
RUN brew install infernal
RUN brew install iqtree
RUN brew install iva
RUN brew install jellyfish-1.1
RUN brew install jellyfish
RUN brew install jpeg



RUN brew install kaiju \
kallisto \
kat \
kent-tools \
kmacs \
kmc \
kmergenie \
kmerstream \
kollector \
kraken
RUN brew install last \
libbigwig \
libpll \
libsequence \
libtool \
lighter \
links-scaffolder \
# lobstr \ fix test later
lrsim \
lsd \
lua \
lumpy-sv
