#!/bin/sh

if [ "$1" = "-c" ];then
        cmd=`echo $2 | grep "rsync\|scp"`
        if [ -z "$cmd" ]; then
                echo "======================================================="
                echo "           Welcome to BCGSC ORCA Service          "
                echo "Only direct rsync or scp file transfer commands allowed"
                echo "======================================================="
        else
            	exec $2
        fi
else

        USER=$(id -un)
        TEAM=$(id -gn)

        echo "Welcome to GSC ORCA Phase 2, USER $(id -un), Your home directory is mounted under /home/hackseq17/$USER"
        echo "Currently installed tools can be found via 'brew list' and '/home/linuxbrew/.linuxbrew/bin' in shell"
        echo "You can remotely transfer data via rsync/scp to your /home/hackseq17/$USER directory"
        echo "Your Hackathon project folder is mounted under /$TEAM, please keep your raw data, scripts here"
   
        exec docker exec -it  -u $(id -u):$(id -g) $(id -gn) /usr/bin/env XAUTHORITY=/home/userhome/$USER/.Xauthority DISPLAY=${DISPLAY} /bin/bash -l
