#!/bin/bash

# script is called to move existing container to another server
# eg call: orca-migrate-container orca1 orca2

NAME=$(id -un)_$UID
USER=$(id -un)
CONTAINER_HOSTNAME=$(id -un)-ORCA
ORCA1=$USER@orca01.dmz.bcgsc.ca
ORCA2=$USER@orca02.dmz.bcgsc.ca

USER_CONTAINER=$(docker ps -a --format "{{.ID}}\t{{.Names}}" | grep "$NAME" | cut -f1)

USER_HOST=$1
NEW_HOST=$2

# ======================= Migration =======

if [ $USER_HOST == $NEW_HOST ]; then
    sh $LOGIN_SCRIPT
fi

# Only migrate stopped containers
if [ "$(docker inspect -f '{{.State.Running}}' $USER_CONTAINER)" ]; then
    if [ "$(docker inspect -f '{{.State.Paused}}' $USER_CONTAINER)" ]; then
        docker unpause $USER_CONTAINER
        fi
    docker stop $USER_CONTAINER
fi

docker export $USER_CONTAINER > $USER_CONTAINER.tar
echo "Migrated container $USER_CONTAINER from $USER_LOCATION to $FREE_LOCATION" >&2

# Clean up 
docker rm $USER_CONTAINER

ssh $NEW_HOST
docker import $USER_CONTAINER.tar $USER_CONTAINER
docker run -ti $USER_CONTAINER /bin/bash

exec sh $LOGIN_SCRIPT

