FROM bcgsc/orca-1:latest
LABEL maintainer="sjackan@gmail.com" name="bcgsc/orca-2"

RUN brew update \
&& brew uninstall jdk jdk@8 \
&& rm -rf /home/linuxbrew/.linuxbrew/share/man/ja \
&& brew install \
a5 \
abacas \
abyss \
abyss-explorer \
ace-corrector \
adam \
adapterremoval \
afra \
ale \
andi \
aragorn \
arcs \
arks \
art \
artemis \
ascp \
astral \
augustus \
bali-phy \
bam-readcount \
bamhash \
bamm \
bamtools \
bamutil \
barrnap \
bazam \
bbtools \
bcalm \
bcftools \
beagle \
beast \
beast2 \
bedops \
bedtools \
beetl \
berokka \
bfc \
bioawk \
biobloomtools \
biomake \
bioperl \
bison \
blast \
blast-legacy \
blat \
bless \
bonsai \
bowtie \
bowtie2 \
bracken \
breseq \
busco \
bwa
