FROM bcgsc/orca-3
RUN brew install m4 \
macse \
mafft \
makedepend 
RUN brew install maker \ 
mapsembler2 \
maq \
mash \
# RUN brew install masurca orca, new version, https://github.com/Homebrew/homebrew-science/pull/5772
mcl \
megahit \ 
meme 
# meraculous \ orca
# RUN brew install metaphlan orca, installed by humann2
RUN brew install mhap \
minced \
minia \
miniasm \
minimap \
mir-prefer \
# RUN brew install mira
mitofy \
mlst \
mothur \ 
mrbayes \
multi-worm-tracker \
mummer \ 
muscle 
# musket no formulae 
RUN brew install nanopolish \
# RUN brew install ncbi-c++-toolkit
ncl \
newick-utils \
newicktools \
nextflow \
nonpareil \
novoalign \
ntcard \
nxtrim 
RUN brew install oases
# RUN brew install ogdraw
RUN brew install oma

RUN brew install orthofinder
